/*
 * Compiled content adapter.
 *
 * In Phase 2 this reads from `modules/blog/content/compiled/` (generated by the
 * compiler). For now it returns an empty array so the rest of the project
 * compiles and renders.
 */

import type { ContentRepository } from "../application/ports/content-repository.ts";
import type { Post } from "../domain/post.ts";

const createCompiledContentRepository = (): ContentRepository => ({
  getAllPostSummaries: () => [],
  getPostBySlug: (_slug: string): Post | null => null,
});

export { createCompiledContentRepository };
